[package]
name = "rust_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
json = "0.12"          # JSONライブラリを使用するため
csv = "1.0"            # CSVライブラリを使用するため
sqlparser = "0.25.0"   # SQL解析ライブラリを使用するため